"""empty message

Revision ID: 665c2064c5aa
Revises: a39903a074bd
Create Date: 2022-06-08 13:52:35.229514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665c2064c5aa'
down_revision = 'a39903a074bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'date')
    # ### end Alembic commands ###
