"""empty message

Revision ID: 1c8fbd05eae2
Revises: 6624d7ca4c4a
Create Date: 2022-06-07 09:57:54.769786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1c8fbd05eae2'
down_revision = '6624d7ca4c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    taxonrank_enum = postgresql.ENUM('KINGDOM', 'PHYLUM', 'CLASS', 'ORDER', 'FAMILY', name='taxonrank', create_type=False)
    taxonrank_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('taxon_classes', sa.Column('rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=False))
    op.add_column('taxon_classes', sa.Column('parent_rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=True))
    op.add_column('taxon_families', sa.Column('rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=False))
    op.add_column('taxon_families', sa.Column('parent_rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=True))
    op.add_column('taxon_kingdoms', sa.Column('rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=False))
    op.add_column('taxon_kingdoms', sa.Column('parent_rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=True))
    op.add_column('taxon_orders', sa.Column('rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=False))
    op.add_column('taxon_orders', sa.Column('parent_rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=True))
    op.add_column('taxon_phyla', sa.Column('rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=False))
    op.add_column('taxon_phyla', sa.Column('parent_rank', sa.Enum('taxon_kingdom', 'taxon_phylum', 'taxon_class', 'taxon_order', 'taxon_family', name='taxonrank'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon_phyla', 'parent_rank')
    op.drop_column('taxon_phyla', 'rank')
    op.drop_column('taxon_orders', 'parent_rank')
    op.drop_column('taxon_orders', 'rank')
    op.drop_column('taxon_kingdoms', 'parent_rank')
    op.drop_column('taxon_kingdoms', 'rank')
    op.drop_column('taxon_families', 'parent_rank')
    op.drop_column('taxon_families', 'rank')
    op.drop_column('taxon_classes', 'parent_rank')
    op.drop_column('taxon_classes', 'rank')

    taxonrank_enum = postgresql.ENUM('KINGDOM', 'PHYLUM', 'CLASS', 'ORDER', 'FAMILY', name='taxonrank', create_type=False)
    taxonrank_enum.drop(op.get_bind())
    # ### end Alembic commands ###
