"""empty message

Revision ID: 6624d7ca4c4a
Revises: d633d5ff1fe1
Create Date: 2022-06-06 23:58:54.468789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6624d7ca4c4a'
down_revision = 'd633d5ff1fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon_classes', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('taxon_families', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('taxon_kingdoms', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('taxon_orders', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('taxon_phyla', sa.Column('external_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxon_phyla', 'external_id')
    op.drop_column('taxon_orders', 'external_id')
    op.drop_column('taxon_kingdoms', 'external_id')
    op.drop_column('taxon_families', 'external_id')
    op.drop_column('taxon_classes', 'external_id')
    # ### end Alembic commands ###
